services:
  - type: web
    name: jit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DROPBOX_APP_KEY
        value: 2bi422xpd3xd962
      - key: DROPBOX_APP_SECRET
        value: j3yx0b41qdvfu86
      - key: DROPBOX_REFRESH_TOKEN
        value: RvyL03RE5qAAAAAAAAAAAVMVebvE7jDx8Okd0ploMzr85c6txvCRXpJAt30mxrKF
    healthCheckPath: /health
    autoDeploy: true